#!/bin/bash

function fact {
if [ $1 -eq 1 ]
then echo 1
elif [ $1 -eq 0 ]
then echo 1
else
calc=$(( $1-1 ))
res=$(fact $calc)
echo $(( $res * $1 ))
fi
}

check='^[0-9]+$'
read -p "Enter value: " val
if ! [[ $val =~ $check ]]
then echo "Error: Enter the correct number" >&2;
exit 1
fi
res=$(fact $val)
echo "Result: $res"
